### ISSUE TITLE
Support filter or identifier for runc containers

### ISSUE THREAD

**Issue by wunder957** [hitsz-ids/duetector#45]
Currently, since the `runc` container shares kernel with each other and host, information about the host will be collected under the `runc` container, and we need a way to filter it to support cloud-native environments.

Reference:

https://github.com/cilium/cilium
https://github.com/deepflowio/deepflow

**Comment by wunder957** [comment]
Under docker, the ebpf-independent approach requires some `capabilities` as well as `--pid` for pid namespace.

In k8s, we can use `hostPID` for pid namespace.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: <name>
spec:
  - hostPID: true
```
